exclude_patterns:
  - "**/migrations/"
  - "**/tests/"
  
  plugins:
  duplication:
    enabled: false
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 50
